version: '2'
services:
     
  door_status:
    build:
      context: .
    image: door_status:1.0
    restart: unless-stopped
    command: node index.js
    volumes:
      - /sys/devices/platform/soc/20200000.gpio:/sys/devices/platform/soc/20200000.gpio
      - /sys/class/gpio:/sys/class/gpio
    ports:
      - 8080:8080
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

# instructions:
# build: docker-compose build
# start: docker-compose up -d 
# stop: docker-compose down
# list running containers: docker-compose ps
